### ISSUE TITLE
Unknown exception occurred on executing models/puzzles/einstein/einstein-wikipedia.als

### ISSUE THREAD

**Issue by ligurio** [AlloyTools/models#16]
https://github.com/AlloyTools/models/blob/master/puzzles/einstein/einstein-wikipedia.als

```
   Sig this/House forced to have exactly 5 atoms.
Unknown exception occurred:
java.lang.UnsupportedOperationException
```

Alloy Analyzer 6.1.0 built 2021-11-03T15:25:43.736Z

**Comment by grayswandyr** [comment]
I seem to recall meta-operations (like `House$.subfields`) don't work in Alloy 6. Maybe this is a good opportunity to not only fix but also improve this.

**Comment by grayswandyr** [comment]
On the short term, you can make the model work without meta-operations. On the longer term, I (sometimes) think that having a more sophisticated meta- or macro language would be nice.
