### ISSUE TITLE
Warning in basic-auth.als

### ISSUE THREAD

**Issue by lionello** [AlloyTools/models#9]
Got a warning when executing the `basic-auth` model using Alloy 5.1.0:
```
Subset operator is redundant, because the left and right
subexpressions are always disjoint.
Left type = {this/Challenge}
Right type = {this/Credentials}
```

https://github.com/AlloyTools/models/blob/969f5f809c33c5f70e10b2aae1c747f6a10eac86/ietf-rfcs/rfc7617-BasicAuth/basic-auth.als#L164

I suspect the code that was intended is:
```
	all b : Challenge | b in WWWAuthenticate.challenges.elems
```

**Comment by pkriens** [comment]
thanks, fixed
